data:
  account_url: https://firefighterdata.blob.core.windows.net
  azure_container_name: data
  path_old_data: oldies/
  current_table: newest_table.parquet
  online_address: https://data.london.gov.uk/download/london-fire-brigade-incident-records/f5066d66-c7a3-415f-9629-026fbda61822/LFB%20Incident%20data%20Last%203%20years.csv
  local_train_data: data/train.parquet
  local_test_data: data/test.parquet
  api_directory: api/
  train_old: train/old/
  train_newest: train/train.parquet
  test_old: test/old/
  test_newest: test/test.parquet

api:
  requests: api/requests/
  responses: api/responses/
  key_vault_url: https://mlops-credentials.vault.azure.net/
