version: '3'
services:
  modeling:
    build:
      context: ./modeling
    volumes:
      - ./data:/app/data
      - ./config.yml:/app/config.yml:ro
    env_file:
      - .env

  api:
      build:
        context: ./api
      ports:
        - "8000:8000"
      volumes:
        - ./data:/app/data
        - ./config.yml:/app/config.yml:ro
      env_file:
        - .env
      depends_on:
        modeling:
          condition: service_completed_successfully