name: MLOps Fire Fighter CI/CD

permissions:
    contents: read
    pages: write
    id-token: write

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: 3.8
    - run: |
        python3 -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Run tests
      run: |
        export PYTHONPATH="${{ env.WORKSPACE }}:${{ env.PYTHONPATH }}"
        python3 -m utils.tests.test_helpers
        python3 -m utils.tests.test_model_pipeline
        python3 -m utils.tests.test_train_predict_model
        python3 -m utils.tests.test_data_collection
    - run: python3 -m pytest